pub mod toggle;

pub use toggle::{
    Toggle, ToggleStyle, TOGGLE_ANIM_SECONDS, TOGGLE_BOX, TOGGLE_BOX_RADIUS, TOGGLE_GAP,
    TOGGLE_ICON_BOX, TOGGLE_ICON_GLYPH, TOGGLE_ICON_RADIUS, TOGGLE_KNOB_PAD,
    TOGGLE_KNOB_W_RATIO, TOGGLE_LABEL_SIZE, TOGGLE_OFF_DARK, TOGGLE_OFF_LIGHT,
    TOGGLE_SWITCH_H, TOGGLE_SWITCH_W,
};
