pub mod circular;
pub mod gauge;
pub mod linear;

pub use circular::{
    CircularGauge, CIRC_DOT_R, CIRC_FILL, CIRC_KNOB_R, CIRC_KNOB_RING_R, CIRC_LABEL_SIZE,
    CIRC_RING_R, CIRC_START, CIRC_SWEEP, CIRC_TRACK_W, CIRC_VALUE_SIZE,
};

pub use linear::{
    LinearGauge, LINEAR_DOT_R, LINEAR_KNOB_R, LINEAR_RING_R, LINEAR_TRACK_H,
    LINEAR_VALUE_GAP, LINEAR_VALUE_SIZE,
};
pub use gauge::{
    Gauge, GAUGE_ANIM_SECONDS, GAUGE_FILL, GAUGE_RADIUS, GAUGE_SIDE_GAP, GAUGE_SIDE_SIZE,
    GAUGE_TITLE_GAP, GAUGE_TITLE_SIZE, GAUGE_TRACK_DARK, GAUGE_TRACK_H, GAUGE_TRACK_LIGHT,
    GAUGE_VALUE_GAP, GAUGE_VALUE_SIZE,
};
