pub mod gauge;

pub use gauge::{
    Gauge, GAUGE_ANIM_SECONDS, GAUGE_FILL, GAUGE_RADIUS, GAUGE_SIDE_GAP, GAUGE_SIDE_SIZE,
    GAUGE_TITLE_GAP, GAUGE_TITLE_SIZE, GAUGE_TRACK_DARK, GAUGE_TRACK_H, GAUGE_TRACK_LIGHT,
    GAUGE_VALUE_GAP, GAUGE_VALUE_SIZE,
};
